# -*- coding: utf-8 -*-
"""dicionarios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HadDC63QkjueiuGFfYt3ZVKNWA0OT1rR
"""

pessoa = {
    "Nome": 'Liz',
    "Idade": 20,
    "Peso": 60,
    "Altura": 1.75
}

pessoa

#Acesso
print(f"A idade dessa pessoa é {pessoa['Idade']} anos")
print(f"A altura dessa pessoa é {pessoa['Altura']}m")

#Dicionario dentro de um dicionario
time = {
    "Nome": "Atletico-MG",
    "Liga": "Brasileirão",
    "Jogadores": {
        "Hulk": "Atacante",
        "Nacho": "Meio",
        "Arana": "Lateral"
    }
}
#Saida
print(f"O jogador Hulk do {time['Nome']} joga na posição {time['Jogadores']['Hulk']}")
print(time)

#Tipos de listagem

 escritores = {
     "Monteiro Lobato" : "Sitio do Pica-Pau Amareo",
     "José de Alencar": "O Guarani",
     "Carlos Drummond": "A rosa do Povo"
 }

 #Listar os valores

 print(escritores.values())

 #Listar as chaves
 print(escritores.keys())

#Listar valores e chaves
 print(list(escritores[0]))

"""## **Lista de exercícios**"""

#1
agapornis = {
  "nome_cientifico": "Agapornis",
  "vida_media": 15,
  "vida_max": 20,
  "reserva": {
    "espécies": {
      "1": {
        "nome": "roseicollis",
        "qtd": 20,
      },
      "2": {
        "nome": "personatus",
        "qtd": 1,
      },
      "3": {
        "nome": "fischeri",
        "qtd": 12,
      },
      "4": {
        "nome": "lilianae",
        "qtd": 8,
      },
      "5": {
        "nome": "nigrigenis",
        "qtd": 5,
      },
      "6": {
        "nome": "canus",
        "qtd": 24,
      },
      "7": {
        "nome": "taranta",
        "qtd": 15,
      },
      "8": {
        "nome": "pullarius",
        "qtd": 7,
      },
      "9": {
        "nome": "swindernianus",
        "qtd": 1,
      }
    }
  }  
}

#Inserindo o número referente a espécie
especie = (input('Informe o id da espécie (1 à 9): '))
nascidos = int(input((f"Informe a quantidade de 'agapornis {agapornis['reserva']['espécies'][especie]['nome']}' nascidos ")))
faleceram = int(input((f"Informe a quantidade de 'agapornis {agapornis['reserva']['espécies'][especie]['nome']}' que faleceram ")))

#Atualizando a base
novo_dado = agapornis['reserva']['espécies'][especie]['qtd'] + nascidos - faleceram

#Imprimindo o dado atualizado
print(f"Os registros das aves 'agaporanis {agapornis['reserva']['espécies'][especie]['nome']}' foram atualizados, há {novo_dado} aves.")

#2
filme_1 = {
  "titulo": "O castelo animado",
  "diretor": "Hayao Miyazaki",
  "ano": "2004"
}

filme_2 = {
  "título": "Sussuros do coração",
  "diretor": "Yoshifumi Kondô",
  "ano": "1995" 
}

filme_3 = {
  "título": "Princesa Monoke",
  "diretor": "Hayao Miyazaki",
  "ano": "1999"
}

filme_4 = {
    "título": "O conto da Princesa Kaguya",
    "diretor": "Isao Takahata",
    "ano": "2015"   
}

#criando uma lista com dicionarios
ghibli_filmes = [filme_1, filme_2, filme_3, filme_4]
for i in ghibli_filmes:
  print(i)

#3 

palavras = ["bonito", "feliz", "baixo", "magro", "amor", "salgado"]
antonimos = ["feio", "triste", "alto", "gordo", "ódio", "doce"]

#Transformar duas listas em um dicionario
pares_antonimos = dict(zip(palavras, antonimos))
pares_antonimos

for key, values in pares_antonimos.items():
  print(f"O oposto de {key} é {values} ")

#4

dados_usuario = {
    "nome": "a",
    "idade": "b",
    "altura": "c",
    "massa": "d"
}

laudo = 0

nome = input('Digite seu nome: ')
dados_usuario["nome"]= nome

idade = int(input(('Digite sua idade: ')))
dados_usuario["idade"] = idade

altura = float(input('Digite sua altura: '))
dados_usuario["altura"] = round(altura,2)

massa = float(input('Digite seu peso: '))
dados_usuario["massa"] = massa

IMC = massa /(altura**2)

if 18.5 <= IMC <= 24.9:
  dados_usuario["IMC"] = round(IMC,2)
  laudo = "Normal"

if 25 <= IMC <= 29.9:
  dados_usuario["IMC"] = round(IMC,2)
  laudo = "Sobrepeso"

if 30 <= IMC <= 40:
  dados_usuario["IMC"] = round(IMC,2)
  laudo = "Obesidade"

if IMC > 40.0:
  dados_usuario["IMC"] = round(IMC,2)
  laudo = "Obesidade grave"

print(dados_usuario)

print(f"{dados_usuario['nome']}, seu indice de massa corpórea foi de {IMC:.2f}, classificado como {laudo} ")